http:
  routers:
    app:
      rule: "Host(`app.local`)"
      service: app
      entryPoints:
        - web
  
  services:
    app:
      loadBalancer:
        servers:
          - url: "http://app_app:80"
