http:
  routers:
    covoit:
      rule: "Host(`covoit.local`)"
      service: covoit
      entryPoints:
        - web
  
  services:
    covoit:
      loadBalancer:
        servers:
          - url: "http://covoit_covoit:80"
