---
# ============================================================
# Handlers - Déclenchés par les tâches (notify)
# ============================================================

- name: Restart Docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
  listen: "Restart Docker"
