version: '3.8'

services:
  covoit:
    image: 192.168.56.10/my_app/app-php:1.2
    networks:
      - traefik-net
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covoit.rule=Host(`app.local`)"
        - "traefik.http.routers.covoit.entrypoints=websecure"
        - "traefik.http.routers.covoit.tls=true"
        - "traefik.http.services.covoit.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-net"
    environment:
      - DB_HOST=192.168.56.112
      - DB_PORT=3306
      - DB_NAME=covoit
      - DB_USER=covoit_user
      - DB_PASSWORD=motdepasse

networks:
  traefik-net:
    external: true
