---
# 1. Mise à jour du cache APT
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# 2. Installation des prérequis
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present

# 3. Ajout de la clé GPG Docker
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# 4. Ajout du dépôt Docker
- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

# 5. Mise à jour après ajout du dépôt
- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

# 6. Installation de Docker CE
- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# 7. Installation du SDK Python Docker
- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

# 8. Ajout de l'utilisateur vagrant au groupe docker
- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

# 9. Configuration du Insecure Registry (Harbor HTTP)
- name: Configure Docker daemon for insecure registry
  copy:
    content: |
      {
        "insecure-registries" : ["192.168.56.10:80", "192.168.56.10"]
      }
    dest: /etc/docker/daemon.json
  notify: Restart Docker

# 10. Désactivation du pare-feu pour éviter les blocages Swarm/DB
- name: Disable UFW
  service:
    name: ufw
    state: stopped
    enabled: no
