version: "3.8"

services:
  app:
    image: harbor.local/my_app/app-php:1.0
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`app.local`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.services.app.loadbalancer.server.port=80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  traefik-net:
    external: true
